<?php

use Spatie\LaravelSettings\Migrations\SettingsMigration;

return new class extends SettingsMigration
{
    public function up(): void
    {
        $this->migrator->add('general.hotel_name', 'Apartments Manager');
        $this->migrator->add('general.logo', null);
        $this->migrator->add('general.branch_no', "4546521");
        $this->migrator->add('general.phone', "012345678910");
        $this->migrator->add('general.commercial_register', "MT45132621");
        $this->migrator->add('general.tax_number', "132165341352");
        $this->migrator->add('general.checkout_default_time', "13:00");

        $this->migrator->add('general.reservation_lease_terms', [
            'en' => 'Riam Real Estate Suites places the confidentiality of the information of its users and guests at the top of the list of priorities, and the management makes every effort to provide high quality service to all guests. Guests must constantly review the terms and principles of privacy and confidentiality of information with the General Real Estate Authority and the Saudi Tourism Authority to see any updates to them, bearing in mind that they are not required to announce any updates to these conditions and principles, and your hiring means that you have seen and agreed to those terms and principles and what is done on them. Continuous adjustments. When you stay, we collect and process your personal data for the following purposes (i) checking you in and checking out of the hotel, (ii) assigning an access card to your room or allowing you to use your mobile device as your room key, (iii) obtaining a security with your credit card or a hotel deposit To ensure payment for your stay, (iv) manage (and archive) your hotel check-in card, (v) create or update your profile in our hotel management system, (vi) assess and manage if you meet the requirements for a room upgrade, (vii) manage Payment for your accommodation, (8) preparing, printing or sending an invoice for your accommodation, (9) paying a commission to the travel agent you booked through (in the case of booking through a travel agent). In the event that you book a room in one of our hotels and do not show up on the day of arrival that you notify us, without canceling, we will process your personal data for the following two purposes: (i) to cancel your stay and any other booking you may have made, and (ii) to administer, process and settle any outstanding amounts owed. In the event that you are contacted on the day of departure at two o\'clock in the afternoon, the door to the room will be opened to view it, and this is one of the rights to make sure that it is vacant or occupied, noting that leaving after six o\'clock in the evening will be charged at the price of a full night. It is strictly forbidden to smoke shisha and cigarettes in the room. In the event of smoking, a fine of two hundred riyals will be imposed. It is forbidden to take or bring cooking materials to the hotel, such as gas and the like. The institution has the right to evacuate your belongings from the room if the specified time is exceeded.',

            'ar' => 'تضع مؤسسة اجنحة ريام العقارية سرية معلومات مستخدميها ونزلائها على رأس قائمة الأولويات، وتبذل الإدارة كل جهودها لتقديم خدمة ذات جودة عالية لكل النزلاء. يجب على النزلاء الاطلاع المستمر على شروط ومبادئ الخصوصية وسرية المعلومات لدى الهيئة العامة للعقار والهيئة السعودية للسياحة لمعرفة أي تحديثات تتم عليها، علماً بأنهم غير مطالبين بالإعلان عن أية تحديثات تتم على تلك الشروط والمبادئ، واستئجارك يعني اطلاعك وموافقتك على تلك الشروط والمبادئ وما يتم عليها من تعديلات مستمرة. عند الإقامة، فإننا نجمع بياناتك الشخصية ونعالجها للأغراض التالية (1) تسجيل وصولك إلى الفندق وتسجيل مغادرتك له، (2) تخصيص بطاقة دخول لغرفتك أو السماح لك باستخدام جهازك الجوال مفتاحًا لدخول غرفتك، (3) الحصول على ضمان باستخدام بطاقتك الائتمانية أو وديعة للفندق لضمان دفع مقابل إقامتك، (4) إدارة بطاقة تسجيلك في الفندق (وأرشفتها)، (5) إنشاء ملفك التعريفي أو تحديثه في نظامنا لإدارة الفنادق، (6) تقييم مدى استيفائك لشروط ترقية الغرف وإدارة ذلك إذا كنت مستوفيًا للشروط، (7) إدارة سداد مقابل إقامتك، (8) إعداد فاتورة إقامتك أو طباعتها أو إرسالها، (9) سداد عمولة إلى وكيل السفر الذي حجزت عن طريقه (في حالة الحجز عن طريق وكيل سفر). في حالة حجزك غرفة في أحد فنادقنا وعدم حضورك في يوم الوصول الذي أبلغتنا به، دون الإلغاء، فإننا سنعالج بياناتك الشخصية للغرضين التاليين: (1) إلغاء إقامتك وأي حجز آخر قد تكون أجريته، و(2) إدارة أي مبالغ مستحقة غير مسدَّدة ومعالجتها وتسويتها. في حالة الاتصال بك يوم المغادرة الساعه الثانية ظهرًا، سيفتح باب الغرفة للاطلاع عليها وهذا حق من حقوق التآكد من انها شاغرة او مشغولة، علمًا ان المغادرة بعد الساعة السادسة مساءً سيحتسب بسعر ليلة كاملة. يمنع تدخين الشيشة والسجائر في الغرفة منعا باتًا وفي حال التدخين سيتم فرض غرامة قدرها مئتين ريال. يمنع اصطحاب او ادخال مواد طبخ الى الفندق كالغاز ونحوه. للمؤسسة الحق في اخلاء مقتنياتك من الغرفة حال تجاوز الوقت المحدد.'
        ]);
    }
};