<?php

return [
    'apartments' => [
        'types' => [
            1 => "Single Room",
            2 => "Double Room",
            3 => "Twin Room",
            4 => "Twin/Double Room",
            5 => "Triple Room",
            6 => "Four Person Room",
            7 => "Family Room",
            8 => "Suite",
            9 => "Studio",
            10 => "Apartment",
            11 => "Dormitory Room",
            12 => "Bed In Dormitory Room",
            13 => "Hut",
            14 => "Chalet",
            15 => "Villa",
            16 => "Vacation Home",
            17 => "Mobile Home",
            18 => "Tent",
        ],

        'descriptions' => [
            1 => "Business Double Room with Fitness Center Access",
            2 => "Economy Double Room",
            3 => "Double Room with Patio",
            4 => "Deluxe Room (1 Adult + 2 Children)",
            5 => "Deluxe Room (1 Adult + 1 Child)",
            6 => "Deluxe Room (2 Adults + 1 Child)",
            7 => "Deluxe Queen Room",
            8 => "Deluxe King Room",
            9 => "Deluxe Double Room",
            10 => "Deluxe Double Room (1 Adult + 2 Children)",
            11 => "Deluxe Double Room (1 Adult + 1 Child)",
            12 => "Deluxe Double or Twin Room",
            13 => "Deluxe Double Room with Sea View",
            14 => "Deluxe Double Room with Side Sea View",
            15 => "Deluxe Double Room with Castle View",
            16 => "Deluxe Double Room with Bathtub",
            17 => "Deluxe Double Room with Shower",
            18 => "Deluxe Double Room with Extra Bed",
            19 => "Deluxe Double Room with Balcony",
            20 => "Deluxe Double Room with Balcony and Sea View",
            21 => "Deluxe Room",
            22 => "Superior Queen Room",
            23 => "Superior King Room",
            24 => "Superior Double Room",
            25 => "Deluxe Double Room (2 Adults + 1 Child)",
            26 => "Standard Queen Room",
            27 => "Standard King Room",
            28 => "Standard Double Room",
            29 => "Standard Double Room with Shared Bathroom",
            30 => "Standard Double Room with Fan",
            31 => "Queen room",
            32 => "Queen Room - Disability Access",
            33 => "Queen Room with Pool View",
            34 => "Queen Room with Sea View",
            35 => "Queen Room with Garden View",
            36 => "Queen Room with Shared Bathroom",
            37 => "Queen Room with Spa Bath",
            38 => "Queen Room with Balcony",
            39 => "King room",
            40 => "King Room - Disability Access",
            41 => "King Room with Sea View",
            42 => "King Room with Lake View",
            43 => "King Room with Mountain View",
            44 => "King Room with Garden View",
            45 => "King Room with Pool View",
            46 => "King Room with Spa Bath",
            47 => "King Room with Roll-In Shower - Disability Access",
            48 => "King Room with Balcony",
            49 => "Double Room",
            50 => "Double Room (1 Adult + 1 Child)",
            51 => "Double Room - Disability Access",
            52 => "Double Room with Balcony (3 Adults)",
            53 => "Small Double Room",
            54 => "Large Double Room",
            55 => "Double Room with Lake View",
            56 => "Double Room with Pool View",
            57 => "Double Room with Sea View",
            58 => "Double Room with Mountain View",
            59 => "Double Room with Garden View",
            60 => "Double Room with Terrace",
            61 => "Double Room with Private Bathroom",
            62 => "Double Room with Private External Bathroom",
            63 => "Double Room with Shared Bathroom",
            64 => "Double Room with Spa Bath",
            65 => "Double Room with Extra Bed",
            66 => "Double Room with Balcony",
            67 => "Double Room with Balcony (2 Adults + 1 Child)",
            68 => "Double Room with Balcony and Sea View",
            69 => "Double Room with Shared Toilet",
        ],
    ],

    'reservations' => [
        'types' => [
            1 => "Daily",
            2 => "Weekly",
            3 => "Monthly",
        ],

        'id_types' => [
            1 => "National Identity",
            2 => "Family Identity",
            3 => "Gulf Identity",
            4 => "Residence Identity",
            5 => "Passport",
            6 => "Visitor Identity",
        ],

        'payment_methods' => [
            1 => "Cash",
            2 => "Visa",
            3 => "MasterCard",
            4 => "Mada",
        ],
    ],
];